### PR TITLE
BIB-46: Dual boot with Rails 7.1

### PR DESCRIPTION
**Pull request by torresga**
# ⚠️ Must follow https://github.com/bikeindex/bike_index/pull/2579

This PR adds the dual boot code to dual boot both Rails 7.0 and Rails 7.1 locally and in CI.

Running rails c and rails s should work as expected with no errors.
The CI should run the tests for Rails 7.1.

You can append `BUNDLE_GEMFILE=Gemfile.next` to a command, i.e. `BUNDLE_GEMFILE=Gemfile.next rails c` to run whatever command using Rails 7.1. 

We will continue to fix the broken build in Rails 7.1 in upcoming PRs.

### CODE REVIEW

File: Gemfile.next.lock [hunk 1]
```diff
@@ -149,7 +159,7 @@ GEM
     brakeman (5.4.1)
     buftok (0.2.0)
     builder (3.3.0)
-    bullet (7.0.1)
+    bullet (7.1.6)
```
Comment (torresga) [inline Gemfile.next.lock:162]: Upgrade `bullet` for Rails 7.1 support: https://github.com/flyerhzm/bullet/blob/main/CHANGELOG.md#710-10062023

**Review by fbuys — COMMENTED** [review]
To early to approve this PR, we should wait for https://github.com/bikeindex/bike_index/pull/2579 to be merged first

File: Gemfile.next.lock [hunk 2]
```diff
@@ -185,7 +195,12 @@ GEM
     crass (1.0.6)
     css_parser (1.7.1)
       addressable
-    database_cleaner (1.7.0)
+    database_cleaner (2.0.2)
```
Comment (torresga) [inline Gemfile.next.lock:198]: We updated `database_cleaner` because we were getting this error in Rails 7.1: 

```
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:deletion)

NoMethodError:
  undefined method `table_name' for ActiveRecord::SchemaMigration:Class
# ./spec/rails_helper.rb:161:in `block (2 levels) in <top (required)>'
```

**Review by mateusdeap — APPROVED** [review]
